### PR TITLE
Update React and Enzyme to latest version

### PR DESCRIPTION
**Pull request by Ernoff**
Tests are all passing and the application is also upgraded to React v16

#14

### CODE REVIEW

**Comment by rwieruch** [comment]
@Ernoff that's awesome! Any chance that you could repeat the PR, but exclude the package-lock.json file before in the .gitignore file? I would merge it afterward! 🎉

**Comment by rwieruch** [comment]
See https://github.com/rwieruch/favesound-redux/commit/44b21838be4ebfb54c8615b97be20eb2ae5e8f58 Feel free to update the README.md too :)

**Comment by Ernoff** [comment]
Okay. What would you like me to add to the README.md ??

**Comment by rwieruch** [comment]
If you have the chance to do it :)

screen shot 2017-10-03 at 21 10 29

**Comment by rwieruch** [comment]
Perfect @Ernoff Thank you so much!

**Pull request merged**
